ARG BTCDBASE_IMAGE=schnitzel/btcd
FROM uselagoon/commons as commons
FROM ${BTCDBASE_IMAGE} as btcd-base

COPY --from=commons /bin/fix-permissions /bin/ep /bin/

COPY btcd-lagoon.conf /etc/btcd.conf

ENV HOME=/home \
    BITCOIN_NETWORK=testnet

RUN mkdir -p /data \
    && fix-permissions /data  \
    && fix-permissions /home \
    && fix-permissions /etc/btcd.conf

ENTRYPOINT [ "" ]

CMD [ "sh", "-c", "ep /etc/btcd.conf && btcd --configfile=/etc/btcd.conf" ]